Release 0.1.0 (#3)
* Remove wait related logic

* Add actual knative functionality

* Remove CODEOWNERS

* Fix ESLint errors

* Build release

* Add proper inputs for CI

* Add cat of the file

* Add simplified envsubst() implementation

* Add action test for job

* Update latest build

* Disable some linters

* Rename action name

* Update README

* Add inputs and outputs section

* Add contributing section

* Fix linter

* Allow details and summary elements

* Disable markdown linting

Prettier should be enough

* Fix natural language linting

* Rename target to container_name

* Remove explicit hedge content

* Update docs

* Rebuild app

* Remove target from CI

* Remove code comments

* Add test for handling no containers

* Simplify test

* Add missing tests

* Rebuild

* Fix test linting

* Increase test coverage

* Add test coverage for addEnvToContainer()

* Forward the output value as action output

* Make output optional and output the file

* Update build

* Use outputs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,9 +44,15 @@ jobs:
         id: npm-ci-test
         run: npm run ci-test
 
-  test-action:
-    name: GitHub Actions Test
+  test-service-action:
+    name: GitHub Actions Test with kind Service
     runs-on: ubuntu-latest
+
+    env:
+      MANIFEST_LOCATION: us-east1
+      MANIFEST_SERVICE_ACCOUNT: my-fake-service-account@example.org
+      MANIFEST_IMAGE: node:lts
+      MANIFEST_INJECTED_VARIABLE: bar
 
     steps:
       - name: Checkout
@@ -57,8 +63,45 @@ jobs:
         id: test-action
         uses: ./
         with:
-          milliseconds: 1000
+          input: ./__tests__/__mocks__/service.yaml
+          env_file: ./__tests__/__mocks__/test.env
 
-      - name: Print Output
-        id: output
-        run: echo "${{ steps.test-action.outputs.time }}"
+      - name: Test if new manifest exists
+        run: |
+          if [ ! -f ${{ steps.test-action.outputs.output }} ]; then
+            echo "File not found!"
+            exit 1
+          fi
+
+          cat ${{ steps.test-action.outputs.output }}
+
+  test-job-action:
+    name: GitHub Actions Test with kind Job
+    runs-on: ubuntu-latest
+
+    env:
+      MANIFEST_LOCATION: eu-west4
+      MANIFEST_SERVICE_ACCOUNT: my-fake-service-account@example.org
+      MANIFEST_IMAGE: node:lts
+      MANIFEST_INJECTED_VARIABLE: baz
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
+
+      - name: Test Local Action
+        id: test-action
+        uses: ./
+        with:
+          input: ./__tests__/__mocks__/job.yaml
+          env_file: ./__tests__/__mocks__/test.env
+
+      - name: Test if new manifest exists
+        run: |
+          if [ ! -f ${{ steps.test-action.outputs.output }} ]; then
+            echo "File not found!"
+            exit 1
+          fi
+
+          cat ${{ steps.test-action.outputs.output }}
